//
// Generated file, do not edit! Created by nedtool 4.6 from Link.msg.
//

#ifndef _LINK_M_H_
#define _LINK_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Link.msg:5</tt> by nedtool.
 * <pre>
 * //
 * // Represents a packet in the network. Link layer packet
 * //
 * packet Link
 * {
 *     unsigned int seq;
 *     unsigned int type;
 * }
 * </pre>
 */
class Link : public ::cPacket
{
  protected:
    unsigned int seq_var;
    unsigned int type_var;

  private:
    void copy(const Link& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Link&);

  public:
    Link(const char *name=NULL, int kind=0);
    Link(const Link& other);
    virtual ~Link();
    Link& operator=(const Link& other);
    virtual Link *dup() const {return new Link(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getSeq() const;
    virtual void setSeq(unsigned int seq);
    virtual unsigned int getType() const;
    virtual void setType(unsigned int type);
};

inline void doPacking(cCommBuffer *b, Link& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Link& obj) {obj.parsimUnpack(b);}


#endif // ifndef _LINK_M_H_

