//
// Generated file, do not edit! Created by nedtool 4.6 from mux.msg.
//

#ifndef _MUX_M_H_
#define _MUX_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>mux.msg:16</tt> by nedtool.
 * <pre>
 * packet Mux
 * {
 *     short line;
 * }
 * </pre>
 */
class Mux : public ::cPacket
{
  protected:
    short line_var;

  private:
    void copy(const Mux& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Mux&);

  public:
    Mux(const char *name=NULL, int kind=0);
    Mux(const Mux& other);
    virtual ~Mux();
    Mux& operator=(const Mux& other);
    virtual Mux *dup() const {return new Mux(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual short getLine() const;
    virtual void setLine(short line);
};

inline void doPacking(cCommBuffer *b, Mux& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Mux& obj) {obj.parsimUnpack(b);}


#endif // ifndef _MUX_M_H_

